In [2]:
[gauss_dens_inv(centers[k], omegas[k], x, p) for k in range(p)]

NameError: name 'gauss_dens_inv' is not defined

In [3]:
gauss_dens_inv(centers, omegas, x, len(x))

NameError: name 'gauss_dens_inv' is not defined

In [4]:
np.linalg.det(omegas)

NameError: name 'np' is not defined

In [5]:
[gauss_dens_inv(centers[k], omegas[k],x, len(x)) for k in [0,1]]

NameError: name 'gauss_dens_inv' is not defined

In [6]:
np.sqrt(np.linalg.det(omegas[0]) / ((2 * np.pi) ** p))

NameError: name 'np' is not defined

In [7]:
np.sqrt(np.linalg.det(omegas) / ((2 * np.pi) ** p))

NameError: name 'np' is not defined

In [8]:
np.dot(np.dot((x.T - centers), omegas), (x.T - centers).T)

NameError: name 'np' is not defined

In [9]:
np.dot(np.dot((x - centers), omegas), (x - centers).T)

NameError: name 'np' is not defined

In [10]:
(x - centers)*omegas

NameError: name 'x' is not defined

In [11]:
np.dot((x.T - centers), omegas)

NameError: name 'np' is not defined

In [12]:
np.dot(np.dot((x - centers),np.dot(np.eye(p),omegas)),((x - centers).T))

NameError: name 'np' is not defined

In [13]:
np.dot((x - centers[0]),omegas[0])*(x-centers[0])

NameError: name 'np' is not defined

In [14]:
[np.dot(np.dot((x.T - centers[k]),omegas[k]),((x.T - centers[k]))) for k in range(3)]

NameError: name 'np' is not defined

In [15]:
np.exp(-0.5 *np.array([np.dot(np.dot((x.T - centers[k]),omegas[k]),((x.T - centers[k]))) for k in range(3)]))

NameError: name 'np' is not defined

In [16]:
x.T-centers

NameError: name 'x' is not defined

In [17]:
def gauss_dens_inv(mu, omega, x, p):
    return np.array([np.sqrt(np.linalg.det(omega) / ((2 * np.pi) ** p)) for k in range(p)]) * np.exp(
        -0.5 * np.array([np.dot(np.dot((x.T - mu[k]), omega[k]), (x.T - mu[k]).T) for k in range(p)]))

In [18]:
gauss_dens_inv(centers, omegas, x, 1)

NameError: name 'centers' is not defined

In [19]:
np.array([np.sqrt(np.linalg.det(omegas) / ((2 * np.pi) ** p)) for k in range(p)])

NameError: name 'np' is not defined

In [20]:
np.array([np.dot(np.dot((x.T - centers[k]), omegas[k]), (x.T - centers[k]).T) for k in range(p)])

NameError: name 'np' is not defined

In [21]:
x.T 

NameError: name 'x' is not defined

In [22]:
np.array([np.dot(np.dot((x.T - centers[k]), omegas[k]), (x.T - centers[k]).T) for k in range(3)])

NameError: name 'np' is not defined

In [23]:
a = np.arange(24).reshape(2,3,4)

NameError: name 'np' is not defined

In [24]:
np.apply_over_axes(np.sum, a, [0,1])

NameError: name 'np' is not defined

In [25]:
def test(x):
    return [x,x]

b = np.array([[8,1], [4,3], [5,2]])


NameError: name 'np' is not defined

In [26]:
b = np.random.random_sample((10000, 2))

NameError: name 'np' is not defined

In [27]:
b

NameError: name 'b' is not defined

In [28]:
%timeit np.apply_along_axis(gauss_dens_inv, 1,b, centers[0], omegas[0], p)

NameError: global name 'np' is not defined

In [ ]:
%timeit np.array([gauss_dens_inv(x, centers[0], omegas[0], p) for x in b])

In [29]:
np.array([gauss_dens_inv(x, centers[0], omegas[0], p) for x in b])

NameError: name 'np' is not defined

In [30]:
b = np.random.random_sample((100000, 2))

NameError: name 'np' is not defined

In [31]:
c

NameError: name 'c' is not defined

In [32]:
d = np.array([gauss_dens_inv(x, centers[0], omegas[0], p) for x in b])*c[:,0]

NameError: name 'np' is not defined

In [33]:
c[:,0].shape

NameError: name 'c' is not defined

In [34]:
d.shape

NameError: name 'd' is not defined

In [35]:
tab=[2,3,4]
result=[1] + tab

In [36]:
result

[1, 2, 3, 4]

In [37]:
a = np.array([1,2])

NameError: name 'np' is not defined

In [38]:
b = np.array([[2,3],[4,5]])

NameError: name 'np' is not defined

In [39]:
a*b

NameError: name 'a' is not defined

In [40]:
b*a

NameError: name 'b' is not defined

In [41]:
%timeit [[1.0*b[i][k]/sum(b[i]) for k in range(2)] for i in range(len(b))]

NameError: global name 'b' is not defined

In [42]:
for row in b:
    print row

NameError: name 'b' is not defined

In [43]:
np.sum(b, axis=1, keepdims=True)

NameError: name 'np' is not defined

# ALGO


In [44]:
N=10000
X = 10*np.random.random_sample((N, 2))

NameError: name 'np' is not defined

In [45]:
centers = [[0,0],[10,10], [0,0]]
omegas = [[[1,0],[0,1]],[[2,0],[0,1]], [[1,0],[0,1]]]
pi = [0.1, 0.5, 0.4]
p = len(X[0])
K = len(centers)

NameError: name 'X' is not defined

In [46]:
tau_ = np.array([np.apply_over_axes(gauss_dens_inv, X, 1, centers[k], omegas[k], p ) for k in range(K)])

NameError: name 'np' is not defined

In [47]:
np.exp([1,2])

NameError: name 'np' is not defined

In [48]:
np.exp(1)

NameError: name 'np' is not defined

In [49]:
omega_det = np.linalg.det(omegas)

NameError: name 'np' is not defined

#YOUHOU

In [50]:
%timeit  np.array([np.sqrt(omega_det[k] / ((2 * np.pi) ** p)) * np.exp(-0.5*(np.dot(X-centers[k],omegas[k])*(X-centers[k])).sum(axis =1)) for k in range(3)])

NameError: global name 'np' is not defined

In [ ]:
%timeit  np.array([[gauss_dens_inv(X[i], centers[k], omegas[k], p ) for i in range(len(X))] for k in range(3)])

In [ ]:
type([gauss_dens_inv(X[i], centers[k], omegas[k], p ) for i in range(len(X))][0] )

In [51]:
a == b

NameError: name 'a' is not defined

In [52]:
%timeit np.dot(np.dot(X,omegas[0]),(X).T).diagonal()

NameError: global name 'np' is not defined

In [ ]:
%timeit  np.array([gauss_dens_inv(X[i], centers[0], omegas[0], p ) for i in range(len(X))] )

In [ ]:
%timeit (np.dot(X-centers[0],omegas[0])*(X-centers[0])).sum(axis =1)

In [ ]:
np.array([[1,2,3,4],[5,6,7,8]]).T*np.array([1,2])

In [ ]:
%timeit gauss_dens_inv_all(X,centers[0], omegas[0])

In [ ]:
%timeit np.array([gauss_dens_inv(x, centers[0], omegas[0],p) for x in X])

In [ ]:
np.array([gauss_dens_inv_all(X, centers[k], omegas[k]) for k in range(K)]).shape

In [53]:
#OLD version
def gauss_dens_inv(x, mu, omega, p):
    return np.sqrt(np.linalg.det(omega) / ((2 * np.pi) ** p)) * np.exp(
        -0.5 * np.dot(np.dot((x.T - mu), omega), (x.T - mu).T))

def tauik(x, k):
        return (pi[k]*gauss_dens_inv(x, centers[k], omegas[k], 50))/(sum([pi[j]*gauss_dens_inv(x, centers[j], omegas[j], 50) for j in range(3)]))


In [54]:
%timeit np.array([[ tauik(x, k) for k in range(3)] for x in X])

NameError: global name 'np' is not defined

In [ ]:
%timeit tau(X, centers, omegas,pi)

In [162]:
#New version
def gauss_dens_inv_all(X, center, omega):
    return np.sqrt(np.linalg.det(omega) / ((2 * np.pi) ** p)) * np.exp(-0.5*(np.dot(X-center,omega)*(X-center)).sum(axis =1))

def tau(X, centers, omegas, pi):
    densities = np.array([gauss_dens_inv_all(X, centers[k], omegas[k]) for k in range(len(pi))]).T*pi
    return (densities.T/densities.sum(axis=1)).T
    
#def pi
pi = tau(X, centers, omegas, pi).sum(axis=0)*1/N
t=tau(X, centers, omegas,pi)
#def centers
centers = np.array([(t[:,k]*X.T).sum(axis=1)*1/(N*pi[k]) for k in range(K)])

ValueError: shapes (100,5) and (2,2) not aligned: 5 (dim 1) != 2 (dim 0)

In [55]:
np.pi

NameError: name 'np' is not defined

In [56]:
centers

[[0, 0], [10, 10], [0, 0]]

In [57]:
(t[:,0]*X.T).sum(axis=1)

NameError: name 't' is not defined

In [58]:
np.array([1,2,3])*np.array([[1,2],[3,4],[5,6]]).T

NameError: name 'np' is not defined

In [59]:
X.shape

NameError: name 'X' is not defined

In [60]:
t[:,k].sum()

NameError: name 't' is not defined

In [61]:
%timeit [((X-centers[k]).T*np.sqrt(t[:,k]/t[:,k].sum())).T for k in range(K)]

NameError: global name 'K' is not defined

In [ ]:
Z[0]

In [ ]:
from sklearn.covariance import GraphLassoCV
model = GraphLassoCV(alphas = 2)

In [ ]:
prec_

In [ ]:
        cv = np.linalg.inv(np.cov(X.T) + 1 * np.eye(X.shape[1]))
        if not cv.shape:
            cv.shape = (1, 1)
        omegas = np.tile(cv, (3, 1, 1))

In [ ]:
omegas[0]

#Graph lasso ex

In [65]:
import numpy as np
from scipy import linalg
from sklearn.datasets import make_sparse_spd_matrix
from sklearn.covariance import GraphLassoCV, ledoit_wolf
import matplotlib.pyplot as plt

##############################################################################
# Generate the data
n_samples = 100000
n_features = 100

prng = np.random.RandomState(1)
prec = make_sparse_spd_matrix(n_features, alpha=.98,
                              smallest_coef=.4,
                              largest_coef=.7,
                              random_state=prng)
cov = linalg.inv(prec)
d = np.sqrt(np.diag(cov))
cov /= d
cov /= d[:, np.newaxis]
prec *= d
prec *= d[:, np.newaxis]
X = prng.multivariate_normal(np.zeros(n_features), cov, size=n_samples)
X -= X.mean(axis=0)
X /= X.std(axis=0)

##############################################################################
# Estimate the covariance
emp_cov = np.dot(X.T, X) / n_samples

model = GraphLassoCV()
model.fit(X)
cov_ = model.covariance_
prec_ = model.precision_

In [66]:
prec_

array([[  1.21583646e+00,   1.81744919e-03,   0.00000000e+00, ...,
         -0.00000000e+00,   3.64378465e-04,   2.96174889e-03],
       [  1.81744919e-03,   2.27925505e+00,   0.00000000e+00, ...,
          2.19765832e-03,   0.00000000e+00,  -6.32275965e-01],
       [  0.00000000e+00,   0.00000000e+00,   1.89517332e+00, ...,
          2.06306964e-04,  -0.00000000e+00,   2.24141412e-03],
       ..., 
       [ -0.00000000e+00,   2.19765832e-03,   2.06306964e-04, ...,
          4.80954622e+00,   0.00000000e+00,   0.00000000e+00],
       [  3.64378465e-04,   0.00000000e+00,  -0.00000000e+00, ...,
          0.00000000e+00,   1.42987640e+00,   0.00000000e+00],
       [  2.96174889e-03,  -6.32275965e-01,   2.24141412e-03, ...,
          0.00000000e+00,   0.00000000e+00,   1.79287348e+00]])

In [ ]:
np.random.randint(100, size=(1, 10))

In [ ]:
prec = make_sparse_spd_matrix(20)
cov = linalg.inv(prec)

In [ ]:
k = 50
p = np.random.randint(1000, size=(1, k))
weights = 1.0*p/p.sum()

In [ ]:
weights

In [ ]:
np.random.multinomial(1000000, weights[0], size=1)[0]


In [ ]:
X = 10*np.random.random_sample((N, 2))

In [ ]:
p=2
gauss_dens_inv_all(X, [0,0], np.array([[1,0],[0,1]]))

In [ ]:
[gauss_dens_inv(x, np.array([0,0]).T, np.array([[1,0],[0,1]]),2) for x in X]

In [ ]:
pi = np.pi

In [ ]:
e = np.e

In [ ]:
%timeit sum([(pi+e) for _ in range(1000000)])

In [ ]:
%timeit sum([(np.pi+np.e) for _ in range(1000000)])

In [125]:
from graph_lassov5 import Graph_lasso_Mix, gm_params_generator, gaussM

In [138]:
d = 5
k=3
N= 100

Repartition:  [50 32 18]


In [141]:
from sklearn.mixture import GMM

In [142]:
gmm = GMM(n_components=3)

In [143]:
gmm.fit(X)

GMM(covariance_type='diag', init_params='wmc', min_covar=0.001,
  n_components=3, n_init=1, n_iter=100, params='wmc', random_state=None,
  thresh=None, tol=0.001)

In [144]:
gmm.covars_

array([[ 1.11164245,  1.22208009,  0.85301664,  0.85611208,  0.92054186],
       [ 1.04308007,  0.88392652,  0.47942054,  1.45127539,  1.57978759],
       [ 0.6410101 ,  0.80860992,  0.97067542,  0.66847813,  1.07269136]])

In [145]:
cov

array([[[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ]],

       [[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  1.60906816,  0.        ,  0.        ,  0.78042819],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.78042819,  0.        ,  0.        ,  1.        ]],

       [[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.        ,

In [146]:
from sklearn.datasets import make_sparse_spd_matrix


In [147]:
make_sparse_spd_matrix(5, alpha=0.8)

array([[ 1.69792932,  0.        , -0.83542164,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        , -0.54775271,  0.        ],
       [-0.83542164,  0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        , -0.54775271,  0.        ,  1.30003303,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ]])

In [148]:
lasso = Graph_lasso_Mix()

In [155]:
lasso.fit(X)

Beginning Step:  0
Beginning Step:  1
Beginning Step:  2
Beginning Step:  3
Beginning Step:  4


In [156]:
lasso.omegas

array([[[ 107.48189084,   -3.43979513,   -0.        ,   -0.        ,    0.        ],
        [  -3.43979513,   81.29053614,   29.60610013,   23.27718805,
           -6.10019563],
        [  -0.        ,   29.60610013,   31.61904751,  -20.84947851,
           11.5232691 ],
        [  -0.        ,   23.27718805,  -20.84947851,  118.05601981,    0.        ],
        [   0.        ,   -6.10019563,   11.5232691 ,    0.        ,
          104.52771808]],

       [[  77.87141725,   -0.        ,    0.        ,    0.        ,    0.        ],
        [  -0.        ,  150.67982722,   -0.        ,   -0.        ,    0.        ],
        [   0.        ,   -0.        ,   91.20937279,   -0.        ,   -0.        ],
        [   0.        ,   -0.        ,   -0.        ,  138.9578744 ,   -0.        ],
        [   0.        ,    0.        ,   -0.        ,   -0.        ,
          155.52663596]]])

In [161]:
lasso.tau

<bound method Graph_lasso_Mix.tau of Graph_lasso_Mix(alpha=[10, 10], n_components=2, n_iter=5)>

In [209]:
#New version
def gauss_dens_inv_all(X, center, omega):
    return np.sqrt(np.linalg.det(omega) / ((2 * np.pi) ** p)) * np.exp(-0.5*(np.dot(X-center,omega)*(X-center)).sum(axis =1))

def tau(X, centers, omegas, pi):
    densities = np.array([gauss_dens_inv_all(X, centers[k], omegas[k]) for k in range(len(pi))]).T*pi
    return (densities.T/densities.sum(axis=1)).T
    


In [270]:
d = 5
k=3
N= 100
weights, centers, cov = gm_params_generator(d,k)
omegas = [np.linalg.inv(om) for om in cov]
X = gaussM(weights, centers, cov, N)
p = d

Repartition:  [ 9 65 26]


In [211]:
#def pi
pi = tau(X, centers, omegas, pi).sum(axis=0)*1/N
t=tau(X, centers, omegas,pi)
#def centers
centers = np.array([(t[:,l]*X.T).sum(axis=1)*1/(N*pi[l]) for l in range(k)])

In [271]:
X

array([[ -9.59875289,   2.51600384,   6.26420503,  -7.30392274,
          3.13970329],
       [ 10.17748275,  -0.59339455,  -7.97447739,  -6.41047094,
         -6.17176477],
       [-10.80371473,   2.98296562,   5.78189649,  -9.67840625,
          2.35284213],
       [  4.86750569,   4.85816699,   4.62298526,  -8.08105941,
          3.62792345],
       [  6.8615032 ,  -2.04963435,  -8.85060642,  -5.38709395,
         -5.03860527],
       [  5.7467015 ,  -0.70360896,  -7.20430992,  -5.15352167,
         -3.90205691],
       [  6.55913086,   0.40790713,  -8.31679681,  -5.88703819,
         -4.07509523],
       [  7.25470986,   0.84436354,  -7.47267449,  -5.1359682 ,
         -5.07891159],
       [  6.82549984,  -1.23218427,  -7.42966329,  -5.79499013,
         -5.59983037],
       [  6.68716013,   0.0208521 ,  -7.71363721,  -4.99344326,
         -5.26942845],
       [  3.41709833,   4.54031204,   6.32841011,  -7.42788617,
          3.18009708],
       [  6.31304728,   1.02776186,  -5.739

In [212]:
t2 = [[tauik(X[i], l) for l in range(k)] for i in range(len(X))]

In [213]:
t2[0]

[1.8693364811842272e-18, 1.4190727509655953e-120, 1.0]

In [214]:
t[0]

array([  2.23670446e-019,   2.13389397e-119,   1.00000000e+000])

In [215]:
range(k)

[0, 1, 2]

In [216]:
pi

array([ 0.26,  0.22,  0.52])

In [265]:
lasso.gauss_dens_inv_all(X, centers[0], np.linalg.inv(cov[0]))

ValueError: operands could not be broadcast together with shapes (1000000,50) (2,) 

In [218]:
omegas[0]

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        , -0.42176503],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        , -0.42176503,  0.        ,  0.        ,  1.17788574]])

In [219]:
[np.sqrt(np.linalg.det(omegas[j]) / ((2 * np.pi) ** 5)) for j in range(3)]

[0.010105326013811642, 0.010105326013811641, 0.010105326013811644]

In [220]:
from scipy.stats import multivariate_normal

In [245]:
rv = multivariate_normal(centers[0],np.linalg.inv(centers[0]))

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [ ]:
[rv.pdf(x) for x in X]

In [231]:
np.random.multivariate_normal(centers[0],omegas[0],5000)

array([[-2.21276015,  8.12527231,  3.94494847,  0.9727146 ,  6.36463907],
       [-2.03861843,  6.90572187,  1.7397906 ,  1.17053204,  7.79588793],
       [-3.23740475,  8.96077338,  2.37617402,  2.09956948,  6.4360214 ],
       ..., 
       [-1.16520815,  7.74747385,  2.48164663,  1.04385565,  7.16916565],
       [-0.59985092,  8.84423557,  2.34479435,  0.87713177,  6.82238036],
       [-3.09635851,  8.44025286,  2.16261767,  3.77671221,  7.03923332]])

In [232]:
X

array([[ -4.95806541,   5.51334191,  -5.30695406,  -3.35893478,   6.7156041 ],
       [ -0.61924633,   5.26708184,  -3.50740224,  -3.85670564,
          7.46802132],
       [ -1.77693913,   4.87104334,  -3.74782411,  -3.80457485,   7.1045139 ],
       [ -8.83987262,  -9.6341064 ,  10.25689081,  -9.32327177,
         -5.29856701],
       [ -6.6568889 , -10.29284269,   7.08390705, -10.62465795,
         -3.79184318],
       [ -2.99415314,   9.77052046,   3.38714235,   1.2908428 ,
          9.30611227],
       [ -7.95230693,  -8.21947867,   9.79523591,  -7.5154856 ,  -5.2171976 ],
       [ -6.01769345,  -8.24592755,   9.04966701,  -9.80568693,
         -4.96575937],
       [ -3.2535708 ,   4.38652651,  -3.85247902,  -3.1302131 ,
          7.23151052],
       [ -3.90954287,   3.57781411,  -1.66928577,  -5.13593098,
          7.50928276],
       [ -7.41778663,  -7.44617635,   7.83341831,  -6.81804797,
         -6.38185801],
       [ -1.09852785,   4.34474214,  -4.53869904,  -4.83790554,
   

In [240]:
weights, centers, cov = gm_params_generator(50,3)
X = gaussM(weights, centers, cov, 100000)

Repartition:  [446589 131593 421818]


In [250]:
rv = multivariate_normal(centers[0],cov[0])
#[rv.pdf(x) for x in X]
k = len(pi)

In [258]:
[np.random.multivariate_normal(centers[k], cov[k], rep[k]) for k in range(3)]

[array([[ -3.18517511e+00,  -2.95214802e+00,   3.78365743e+00,
          -8.05968801e-01,  -5.83632151e+00,   8.27135462e+00,
           8.65109370e+00,   3.52883272e+00,   1.00086982e+01,
           6.75072514e+00,   3.79458650e+00,  -4.68570931e+00,
           1.03492414e+00,   6.96143884e+00,   3.95631359e-01,
           8.70926544e+00,   9.78800594e+00,  -2.22168351e+00,
          -2.66917036e+00,  -3.79399076e+00,   6.35874553e-01,
          -1.33997264e+00,   7.58652955e+00,   3.65501885e+00,
           1.94763216e+00,  -5.85424842e+00,  -2.68325190e+00,
           1.95030076e+00,  -4.02400859e+00,  -7.99350902e+00,
           7.88175805e+00,  -9.01461675e+00,   2.51499360e-01,
           4.42805691e+00,  -1.23801749e+01,  -1.86734959e+00,
          -9.08494198e+00,  -1.61079648e-01,  -1.46874020e+00,
           5.24257826e+00,   8.15718164e+00,  -1.14982176e+01,
          -9.52055567e+00,   2.40982827e+00,  -9.37751831e+00,
           3.28359580e+00,   2.22299128e+00,  -2.017632

In [1]:
weights, centers, cov = gm_params_generator(50,2)
rep = np.random.multinomial(1000, weights, size=1)[0]
X = np.random.multivariate_normal(centers[0], cov[0], 1)

NameError: name 'gm_params_generator' is not defined

In [8]:
import numpy as np

In [17]:
%reload_ext autoreload

In [2]:
from graph_lassov5 import gaussian_mixture_sample, gm_params_generator

In [68]:
d = 50
k = 10
N= 10000
weights, centers, cov = gm_params_generator(d,k)
X = gaussian_mixture_sample(weights, centers, cov, N)

In [71]:
a = np.array([np.sqrt(1/((2*np.pi)**d)*np.linalg.det(cov[0]))*np.exp(np.float128(-0.5*np.dot(np.dot(X[i],np.linalg.inv(cov[i])),X[i]))) for i in range(k)])

In [72]:
a/a.sum()

array([ 0.0,  1.7619858e-3346,  0.0,  8.1182231e-1939,  1.1506947e-750,
        3.5699258e-3900,  6.1144547e-350,  2.9608801e-4111,  1.0,
        1.6584451e-830], dtype=float128)

In [19]:
len(X[0])

50

In [12]:
np.linalg.

array([1, 2, 3, 4])

(10, 5)

In [34]:
X

array([[ -6.95433797,  -1.25531156,  -2.69913659,   1.23120841,
         -9.05049726],
       [  0.3607267 ,   0.35409995,   6.05535039,   6.12654252,
         -7.47704891],
       [ 11.01399659,   9.69860498,   3.60927373,   7.36069726,
         -4.34374523],
       [  1.2420602 ,   2.94110808,   5.47997142,  -3.03438121,
        -10.63925573],
       [  0.2269008 ,   8.83010147,  -4.59379119,  -3.3586654 ,
          4.17894152],
       [ -6.39372869,   5.59491485,   7.35511887,  -2.23239049,
          3.02561884],
       [ -6.45604776,  -2.48597661,   9.32084696,  -0.58933603,
          0.10300802],
       [ -8.38511175,  -6.01533336,   5.44692117, -11.47565132,
         -2.66552416],
       [ -0.70940311,   4.90076977,   5.59851865,  -6.30011163,
          0.31648615],
       [ -1.52040383,  -7.08049714,   1.96909085,  -5.32424285,  -9.7660965 ]])

In [ ]:
for i in range(2,len(X)):
    a=np.vstack()

In [46]:
X

array([[ -7.5742501 ,  -3.47635879,  -9.2863342 ,  -4.32977104,
          4.192277  ,  -8.13965656,   6.13014071,   1.84313429,
        -14.4670641 ,  -5.04289994, -15.84552632,   5.25013612,
         -6.94867297,   6.35044477, -12.23504289, -10.07647189,
        -39.46733517,   3.42578906,  -1.77093815,   3.67867662,
        -12.43444071,  -1.11092962,  -4.37119988,   1.60421796,
          2.77341014,  -7.66559977,  -4.53332786, -37.84224072,
         -3.12065984,   5.49367682, -23.27848061,   5.05264472,
         -5.69434799, -30.40200099,  -8.08342744,  -7.63887116,
         -1.96408569, -10.4649998 ,  -5.6741331 ,   2.39090123,
         -3.36649589,   7.78706491,  -4.1827399 ,  -2.00551439,
         -1.24715825,   1.8904835 ,   0.17121405,   5.38232001,
         -7.81330736,   1.0907273 ]])

In [31]:
a = np.array([np.random.multivariate_normal(centers[0], cov[0], 5) for _ in range(3)])

In [33]:
a

array([[[ -3.04528951,   9.27903272,  -6.04523313,  -2.66321616,
           6.01822286],
        [ -4.13531469,   9.90376053,  -7.90476672,  -2.47430077,
           4.24190869],
        [ -2.33225058,  10.6706722 ,  -5.58137365,  -3.88810412,
           5.07409416],
        [ -4.03404327,  10.42886755,  -6.73009751,  -2.55655612,
           5.76061625],
        [ -4.29448506,   8.81430938,  -8.07980924,  -1.97802648,
           7.66149427]],

       [[ -4.14381845,   9.93568821,  -7.70262561,  -2.55478973,
           4.69236774],
        [ -3.10567445,   7.79204003,  -4.38008001,  -2.89577034,
           3.35285297],
        [ -3.22812803,   9.96366819,  -5.85031843,  -3.15504264,
           3.07658627],
        [ -2.2265523 ,   7.59352906,  -4.19144569,  -2.8203604 ,
           7.98775127],
        [ -1.85629768,   6.79300827,  -4.88955482,  -3.30059728,
           5.2579047 ]],

       [[ -4.48057485,   8.10604138,  -6.3824591 ,  -2.57257531,
           4.52087808],
        [ -2.4815

In [21]:
ZX

AttributeError: 'list' object has no attribute 'shape'

In [75]:
a = [1,2,3,4]
b= [5,6,7,8]
import itertools

In [82]:
for u,v in itertools.combinations(range(len(a)),2):
    print i

(0, 1)
(0, 2)
(0, 3)
(1, 2)
(1, 3)
(2, 3)


In [87]:
c = [5,3,2]

In [88]:
sorted(c)

[2, 3, 5]

In [92]:
a = {"a":2, "b":3, "d":1}

In [90]:
a.get(2)

In [93]:
sorted(a, key=a.get)

['d', 'a', 'b']

In [63]:
a = [0, 1, 2, 1, 1, 3, 1, 3]
b = [0, 2, 1, 1, 1, 2, 2, 3]

In [4]:
a1 = {}
b1 = {}

In [7]:
for u,v in enumerate(a):
    a1[u]=v
for u,v in enumerate(b):
    b1[u]=v

In [81]:
a

[0, 1, 2, 1, 1, 3, 1, 3]

In [82]:
b

[0, 2, 1, 1, 1, 2, 2, 3]

In [89]:
def cont_val(y, y_estim, i, j):
    y_idx = []
    for idx,val in enumerate(y):
        if val == i:
            y_idx.append(idx)
    y_estim_idx = []
    for idx,val in enumerate(y_estim):
        if val == j:
            y_estim_idx.append(idx)
    return len(set(y_idx)&set(y_estim_idx))

    

In [90]:
cont_val(a,b,0,1)

0

In [110]:
def cont_matrix(y, y_estim, permut):
    k = len(permut)
    m = np.zeros((k,k))
    for i in range(k):
        for j in range(k):
            m[j,i]=cont_val(y, y_estim, i, permut[j])
    return m

In [96]:
cont_matrix(a,b, [0,3,2,1])

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  2.,  0.,  1.],
       [ 0.,  2.,  1.,  0.]])

In [113]:
def best_cont_matrix(y, y_estim):
    best_permut = list(set(y))
    best_diag_sum = 0
    for permut in permutations(set(y_estim)):
        diag_sum = sum(cont_matrix(y, y_estim, list(permut)).diagonal())
        if diag_sum > best_diag_sum:
            best_permut = list(permut)
            best_diag_sum = diag_sum
    return cont_matrix(y, y_estim, best_permut), best_permut, diag_sum

In [114]:
best_cont_matrix(a,b)

(array([[ 1.,  0.,  0.,  0.],
        [ 0.,  2.,  0.,  1.],
        [ 0.,  2.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]), [0, 2, 1, 3], 3.0)

In [51]:
from itertools import permutations, combinations

In [103]:
[list(i) for i in permutations(set(a))]

[[0, 1, 2, 3],
 [0, 1, 3, 2],
 [0, 2, 1, 3],
 [0, 2, 3, 1],
 [0, 3, 1, 2],
 [0, 3, 2, 1],
 [1, 0, 2, 3],
 [1, 0, 3, 2],
 [1, 2, 0, 3],
 [1, 2, 3, 0],
 [1, 3, 0, 2],
 [1, 3, 2, 0],
 [2, 0, 1, 3],
 [2, 0, 3, 1],
 [2, 1, 0, 3],
 [2, 1, 3, 0],
 [2, 3, 0, 1],
 [2, 3, 1, 0],
 [3, 0, 1, 2],
 [3, 0, 2, 1],
 [3, 1, 0, 2],
 [3, 1, 2, 0],
 [3, 2, 0, 1],
 [3, 2, 1, 0]]

In [53]:
[i for i in combinations(range(4),2)]

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

In [55]:
c = cont_matrix(a,b, [3,2,1])

In [77]:
c[0,1]=1

In [102]:
sum(c.diagonal())

4.0

In [101]:
c[0,0]=3
