In [5]:
import rpy2.robjects as robjects

In [6]:
pi = robjects.r['pi']

In [7]:
type(pi)

rpy2.robjects.vectors.FloatVector

NameError: name 'rpy2' is not defined

In [12]:
import numpy as np

In [13]:
np.array(pi)

array([ 3.14159265])

In [14]:
a = np.array([1,2,3])

In [17]:
v = robjects.FloatVector(a*a)

In [18]:
v

<FloatVector - Python:0x10ec64a28 / R:0x7fe555c7fe90>
[1.000000, 4.000000, 9.000000]

In [22]:
import rpy2.robjects as robjects

r = robjects.r

x = robjects.IntVector(range(10)) 
y = r.rnorm(10)

r.X11()

r.layout(r.matrix(robjects.IntVector([1,2,3,2]), nrow=2, ncol=2)) 
r.plot(r.runif(10), y, xlab='runif', ylab='foo/bar', col='red')



/usr/local/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Error in axis(side = side, at = at, labels = labels, ...) : 
  could not find any X11 fonts
Check that the Font Path is correct.

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/usr/local/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: In addition: 
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/usr/local/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Warning messages:

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/usr/local/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: 1: 
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/usr/local/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: In (function (display = "", width, height, pointsize, gamma, bg,  :
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/usr/local/lib/python2.7/

RRuntimeError: Error in axis(side = side, at = at, labels = labels, ...) : 
  could not find any X11 fonts
Check that the Font Path is correct.


/usr/local/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Error in nrow(s) : argument "s" is missing, with no default

  res = super(Function, self).__call__(*new_args, **new_kwargs)


RRuntimeError: Error in nrow(s) : argument "s" is missing, with no default


ValueError: Error while trying to convert element 0 to a double.

<ListVector - Python:0x10f2812d8 / R:0x7fe5533a33b8>
[Matrix, Matrix, Float..., ..., Vector, Float..., IntVe...]
  w: <class 'rpy2.robjects.vectors.Matrix'>
  <Matrix - Python:0x10f281b00 / R:0x7fe555e90e00>
[0.205245, 0.000000, 0.029851, ..., 0.000000, 0.000000, 0.130732]
  wi: <class 'rpy2.robjects.vectors.Matrix'>
  <Matrix - Python:0x10f281ab8 / R:0x7fe555ea7c00>
[5.668941, 0.000000, -0.000000, ..., 0.000000, 0.000000, 7.671671]
  loglik: <class 'rpy2.robjects.vectors.FloatVector'>
  <FloatVector - Python:0x10f281c20 / R:0x7fe554cae828>
[4621.047936]
  ...
  w: <class 'rpy2.robjects.vectors.Vector'>
  <Vector - Python:0x10f2d90e0 / R:0x7fe55309b378>
[       0]
  wi: <class 'rpy2.robjects.vectors.FloatVector'>
  <FloatVector - Python:0x10f281f80 / R:0x7fe5533a3878>
[0.000000]
  loglik: <class 'rpy2.robjects.vectors.IntVector'>
  <IntVector - Python:0x10f2e4ea8 / R:0x7fe5533a38a8>
[       6]

In [57]:
robjects.FloatVector([[1,2],[3,4]])

ValueError: Error while trying to convert element 0 to a double.

In [45]:
v = robjects.FloatVector([1.1, 2.2, 3.3, 4.4, 5.5, 6.6]) 

print(m) [,1] [,2] [,3][1,] 1.1 3.3 5.5 [2,] 2.2 4.4 6.6

SyntaxError: invalid syntax (<ipython-input-45-bfc6e751a435>, line 2)

In [47]:
help(robjects)

Help on package rpy2.robjects in rpy2:

NAME
    rpy2.robjects - R objects as Python objects.

FILE
    /usr/local/lib/python2.7/site-packages/rpy2/robjects/__init__.py

DESCRIPTION
    The module is structured around the singleton r of class R,
    that represents an embedded R.
    
    License: GPLv3.0 (although a dual license can be worked out)

PACKAGE CONTENTS
    constants
    conversion
    environments
    functions
    help
    language
    lib (package)
    methods
    numpy2ri
    packages
    packages_utils
    pandas2ri
    robject
    tests (package)
    vectors

CLASSES
    __builtin__.object
        R
    rpy2.rinterface.Sexp(__builtin__.object)
        Formula(rpy2.robjects.robject.RObjectMixin, rpy2.rinterface.Sexp)
    rpy2.robjects.robject.RObjectMixin(__builtin__.object)
        Formula(rpy2.robjects.robject.RObjectMixin, rpy2.rinterface.Sexp)
    
    class Formula(rpy2.robjects.robject.RObjectMixin, rpy2.rinterface.Sexp)
     |  Method resolution order:
     |  

In [48]:
robjects.vectors.Matrix([[1,2],[3,4]])

TypeError: The object must be representing an R array

In [50]:
help(robjects.Matrix)

Help on class Matrix in module rpy2.robjects.vectors:

class Matrix(Array)
 |  An R matrix
 |  
 |  Method resolution order:
 |      Matrix
 |      Array
 |      Vector
 |      rpy2.robjects.robject.RObjectMixin
 |      rpy2.rinterface.SexpVector
 |      rpy2.rinterface.Sexp
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  crossprod(self, m)
 |      crossproduct X'.Y
 |  
 |  dot(self, m)
 |      Matrix multiplication
 |  
 |  eigen(self)
 |      Eigen values
 |  
 |  svd(self, nu=None, nv=None, linpack=False)
 |      SVD decomposition.
 |      If nu is None, it is given the default value min(tuple(self.dim)).
 |      If nv is None, it is given the default value min(tuple(self.dim)).
 |  
 |  tcrossprod(self, m)
 |      crossproduct X.Y'
 |  
 |  transpose(self)
 |      transpose the matrix
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  colnames
 |      Column names
 |  
 |  ncol
 |      Numb

In [51]:
data = np.random.random((10,10))

In [56]:
r.heatmap(data)    

/usr/local/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Error in plot.new() : 
  X11 fatal IO error: please save work and shut down R

  res = super(Function, self).__call__(*new_args, **new_kwargs)


RRuntimeError: Error in plot.new() : 
  X11 fatal IO error: please save work and shut down R


In [20]:
import rpy2.robjects.numpy2ri
rpy2.robjects.numpy2ri.activate()
from rpy2.robjects.packages import importr
import numpy as np
rglasso = importr('glasso')
a = np.random.random((100,1000))
c = np.cov(a)
l = rglasso.glasso(c,0.1)[1]

In [21]:
r = np.array(l)

In [23]:
l

<Matrix - Python:0x10cec19e0 / R:0x7fb5a183ae00>
[5.410949, 0.000000, 0.000000, ..., 0.000000, 0.000000, 5.449855]

In [88]:
np.array(l)

array([[ 5.47919303,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  5.46415702,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  5.40999788, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  5.45267675,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         5.41849842,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  5.37119969]])

In [84]:
a

array([[ 0.79107693,  0.88623413],
       [ 0.40755064,  0.40138952],
       [ 0.49056628,  0.84874417],
       [ 0.74412447,  0.77848605],
       [ 0.38884166,  0.07605787],
       [ 0.84849962,  0.03009202],
       [ 0.53804651,  0.68421299],
       [ 0.26037545,  0.93919915],
       [ 0.83163368,  0.2517096 ],
       [ 0.71884098,  0.8577194 ],
       [ 0.11984504,  0.72466798],
       [ 0.03644773,  0.63501637],
       [ 0.62498629,  0.09550742],
       [ 0.77615599,  0.08974722],
       [ 0.13641094,  0.8164804 ],
       [ 0.76553796,  0.44028236],
       [ 0.81832864,  0.39913743],
       [ 0.68942973,  0.30927112],
       [ 0.40356512,  0.91331523],
       [ 0.8856985 ,  0.60185409],
       [ 0.84297895,  0.96056476],
       [ 0.43342667,  0.56965333],
       [ 0.53271862,  0.05855847],
       [ 0.71508172,  0.19474529],
       [ 0.56415467,  0.64682222],
       [ 0.03927752,  0.490736  ],
       [ 0.46807892,  0.41272999],
       [ 0.43362627,  0.06555344],
       [ 0.84656772,

In [28]:
np.dot(a.T,a)/len(a)

array([[ 0.36639289,  0.3073518 ,  0.28989901, ...,  0.26629277,
         0.28078008,  0.27725711],
       [ 0.3073518 ,  0.38309289,  0.27864653, ...,  0.26961587,
         0.27479214,  0.28517282],
       [ 0.28989901,  0.27864653,  0.34068001, ...,  0.24659745,
         0.27017941,  0.25282483],
       ..., 
       [ 0.26629277,  0.26961587,  0.24659745, ...,  0.3171631 ,
         0.24743282,  0.25203878],
       [ 0.28078008,  0.27479214,  0.27017941, ...,  0.24743282,
         0.35465961,  0.26836358],
       [ 0.27725711,  0.28517282,  0.25282483, ...,  0.25203878,
         0.26836358,  0.35846271]])

In [34]:
c1 = np.cov(a)

In [29]:
from rpy2 import robjects

In [31]:
cov2 = robjects.r['cov']

In [37]:
c2 = np.array(cov2(a.T))

In [36]:
np.sum(np.abs(c1-c2))

ValueError: operands could not be broadcast together with shapes (100,100) (1000,1000) 

In [38]:
c2

array([[ 0.08481047,  0.00316603, -0.00572897, ...,  0.00211479,
         0.00433628, -0.00465666],
       [ 0.00316603,  0.08637636, -0.00210324, ...,  0.00234355,
        -0.00550741,  0.00268677],
       [-0.00572897, -0.00210324,  0.0816876 , ..., -0.00105222,
        -0.00075408,  0.00369695],
       ..., 
       [ 0.00211479,  0.00234355, -0.00105222, ...,  0.08903831,
         0.00308375,  0.00136842],
       [ 0.00433628, -0.00550741, -0.00075408, ...,  0.00308375,
         0.08467059,  0.00181294],
       [-0.00465666,  0.00268677,  0.00369695, ...,  0.00136842,
         0.00181294,  0.08349113]])

In [39]:
c1

array([[ 0.08481047,  0.00316603, -0.00572897, ...,  0.00211479,
         0.00433628, -0.00465666],
       [ 0.00316603,  0.08637636, -0.00210324, ...,  0.00234355,
        -0.00550741,  0.00268677],
       [-0.00572897, -0.00210324,  0.0816876 , ..., -0.00105222,
        -0.00075408,  0.00369695],
       ..., 
       [ 0.00211479,  0.00234355, -0.00105222, ...,  0.08903831,
         0.00308375,  0.00136842],
       [ 0.00433628, -0.00550741, -0.00075408, ...,  0.00308375,
         0.08467059,  0.00181294],
       [-0.00465666,  0.00268677,  0.00369695, ...,  0.00136842,
         0.00181294,  0.08349113]])